Get consent before installing
And show ascii

diff --git a/install-dev b/install-dev
--- a/install-dev
+++ b/install-dev
@@ -1,8 +1,28 @@
-echo "Installing git..."
-sudo apt-get update > /dev/null
-sudo apt-get install -y git > /dev/null
+ascii_art='
+________                  __        ___.
+\_____  \   _____ _____  |  | ____ _\_ |__
+ /   |   \ /     \\__   \ |  |/ /  |  \ __ \
+/    |    \  Y Y  \/ __ \|    <|  |  / \_\ \
+\_______  /__|_|  (____  /__|_ \____/|___  /
+        \/      \/     \/     \/         \/
 
-echo "Cloning OMAKUB..."
-git clone https://github.com/basecamp/omakub.git ~/.local/share/omakub > /dev/null
+'
 
-source ~/.local/share/omakub/install.sh
+# Halt on errors
+set -e
+
+echo $ascii_art
+echo "=> Omakub is for fresh Ubuntu 24.04 installations only <="
+
+read -p "Begin install? [Y/n]" yn
+if [[ "$yn" =~ ^[Yy]$ ]]; then
+  echo "Installing git..."
+  sudo apt-get update > /dev/null 2>&1
+  sudo apt-get install -y git > /dev/null 2>&1
+
+  echo "Cloning Omakub..."
+  git clone https://github.com/basecamp/omakub.git ~/.local/share/omakub > /dev/null
+
+  echo "Installation starting..."
+  source ~/.local/share/omakub/install.sh
+fi
